[package]
name = "kvs"
version = "0.1.0"
authors = ["terakoya76 <terako.studio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# test
assert_cmd = "0.11"
predicates = "1.0"
regex = "1.3"
# cli
clap = {version = "2", features = ["yaml"]}
